services:
  - type: web
    name: chatkin-ai-server
    env: node
    rootDir: server
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 20

  - type: web
    name: chatkin-ai-client
    env: node
    rootDir: client
    buildCommand: "npm install && npm run build"
    startCommand: "npm run preview"
    envVars:
      - key: NODE_VERSION
        value: 20
